### ISSUE TITLE
Center default thumbnail

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#26]
I added the LFPH logo as the thumbnail-default.svg file for [posts](https://pr-5-lfph.pantheonsite.io/announcements/).  Can it be centered?

It's also not clear to me what your intentions were around when the default thumbnail in global settings was used and when it wasn't.  The announcements, for example, didn't use this default so I added the file to /images/

**Comment by thetwopct** [comment]
As I remember, you wanted the news fallover image on CNCF to be different than the generic fallover image (something to do with spacing?), so I hardcoded it in and added the image to the /images/ directory. When you created LFPH you probably deleted the image as the logo would have been wrong. Possibly https://github.com/cncf/cncf.io/issues/128

AFAIK this page is the only place the default isn't used, because of the above ticket/issue/fix. Let me know where else you see the issue?

**Comment by cjyabraham** [comment]
Ok.  I recall the larger issue now.  So, [in this case](https://pr-5-lfph.pantheonsite.io/announcements/), could we do something to center the logo?  Or should we create an SVG with some internal top padding?

**Comment by thetwopct** [comment]
> Or should we create an SVG with some internal top padding?

I think thats how you did it before. It just became fixed one day. Looking at CNCF the default seems to have the thumbnail dimensions and be centered inside it - https://dev-cncfci.pantheonsite.io/wp-content/uploads/2020/06/thumbnail-default.svg

**Comment by cjyabraham** [comment]
Do you know how to add padding to an SVG like this?  Or I can ask Alex...

**Comment by thetwopct** [comment]
I typically use Method Draw to edit SVGs as it gives a Photoshop interface to edit https://editor.method.ac

**Comment by cjyabraham** [comment]
I've rewritten this cleanly for Alex #42
