### ISSUE TITLE
Is it possible to add some more space before Latest Tweets in mobile?

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#41]
<img width="347" alt="Screen Shot 2020-07-19 at 1 29 59 PM" src="https://user-images.githubusercontent.com/463160/87867897-03a2df00-c9c4-11ea-97a5-b7ac5c7c4be8.png">

**Comment by thetwopct** [comment]
Related

![20200719130518-Linux Foundation Public Health](https://user-images.githubusercontent.com/10615884/87874289-87f36300-c9c0-11ea-9236-978853801dbd.jpg)

Need to fix multiple line / add wrapping when these columns get too small.

Will add new Section (Column) style

**Comment by thetwopct** [comment]
![20200719152719-Linux Foundation Public Health](https://user-images.githubusercontent.com/10615884/87877118-584e5600-c9d4-11ea-9594-18500a9c6ea0.jpg)

There is now `Section Home` and `Section Home (2 columns)` Blocks. The latter adding more space for the Section titles so they don't wrap so early because of being in a column, as well as adding space between columns on mobile.

Note: Any of the block style variations can currently only be inserted by the top block inserter (not the inline block inserter). This is an issue that is fixed in Gutenberg 8.5 / WP 5.5 where the inserters will be synced properly.
