### ISSUE TITLE
Can you figure out why this svg is so small?

### ISSUE THREAD

**Issue by cjyabraham** [lfph/lfph.io#7]
[See the small Covid Shield logo here](https://pr-5-lfph.pantheonsite.io/join/projects/).
I created it by scraping the code from [here](https://www.covidshield.app/).

**Comment by thetwopct** [comment]
The viewBox for the SVG was set to small dimensions and this was restricting the size. It's strange, as the version you used is different to the version on the Covid Shield website. On the website, it's small, but they control the final size through a CSS class to make it bigger.

To get it working, I imported it in to [Method Draw](https://editor.method.ac), edited the size of the canvas and the icon to match, saved, then cleaned up the SVG code and ran through imageOptim. 

I've noticed a few quirks with SVGs recently. When one is inserted via Image / Media Library in the Block Editor they appear very small regardless of the viewBox settings or any other image settings. And once an SVG image is attached as a featured image and is displayed in the sidebar, the image has a lot of empty height above it (the display box does not fit the SVG properly).

**Comment by cjyabraham** [comment]
I wonder if these anomalies are a result of our [SVG Autocrop process](https://github.com/cncf/svg-autocrop) which is now being performed on all uploaded SVGs.

**Comment by thetwopct** [comment]
OK I've broken this down to 2 issues. On the frontend - Safe SVG inputs the dimensions from the viewBox or width/height attributes of the SVG in to the code when inserted as a featured image. [WordPress.org issue](https://wordpress.org/support/topic/width-height-now-set-as-attributes/). I've applied an img CSS fix, so SVGs will now fill their containers on the frontend regardless of image dimensions. The original image you used only had viewBox and it was set to 20px x 20px, but with the CSS fix, it display nicely.

But there is a problem in the editor and it seems to be caused by SVG Autocrop.

1. When inserting an image, the image dimensions sidebar is updated with the dimensions, and the image is inserted in to the page.
2. When SVG Autocrop plugin enabled, an image is inserted at full size, auto-cropped, the dimensions are updated, then the image is inserted again, _but_ the image dimensions are not applied to the image.
3. Without dimensions the SVG adopts the minimum image size set by Gutenberg editor - 20px. 

Perhaps the `wp_handle_upload_prefilter` is being called too late, and it needs to be called before the image is first inserted and the dimensions are updated.

If the SVG Autocrop plugin is turned off, SVGs are inserted in to the editor and display at a correct size.

**Comment by cjyabraham** [comment]
I've created a [new issue](https://github.com/lfph/lfph.io/issues/19) to get the autocrop plugin fixed.
