### ISSUE TITLE
Activate recorded webinars on Webinars page

### ISSUE THREAD

**Issue by thetwopct** [lfph/lfph.io#98]
There are now two recorded webinars in the webinars post type, but they are not displaying on the frontend of the site.

**Comment by cjyabraham** [comment]
@jennydove would you like us to activate a listing of the Recorded Webinars now similar to [how we have it on CNCF](https://www.cncf.io/webinars/)?  We could just list them for now without the filters and add the filters later?

**Comment by jennydove** [comment]
Yeah, lets go for it. Thanks for following up!

**Comment by cjyabraham** [comment]
@jennydove I've set up [the listing of recorded webinars](https://www.lfph.io/community/webinars/).

Just a note that as you go you may want to set meta info for each webinar so that later when there are a lot, we can set up filters [as we have on CNCF](https://www.cncf.io/webinars/).  This is where you set them:
<img width="564" alt="Screen Shot 2021-01-19 at 10 21 46 AM" src="https://user-images.githubusercontent.com/463160/104979848-35aeff80-5a40-11eb-8a4c-9a0b8251c0a7.png">
